CREATE DATABASE IF NOT EXISTS HACKATHON;
CREATE SCHEMA IF NOT EXISTS PUBLIC.STUDENTS;

-- Created the limited attributes view
CREATE VIEW IF NOT EXISTS HACKATHON.PUBLIC.STUDENTS AS
SELECT * from HACKATHON.PUBLIC.STUDENTS
;



